# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "96a7876af39631ad959c4cca39b1941b"
name = "app-bridge-test"
handle = "app-bridge-test-39"
application_url = "https://mistake-options-purposes-general.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://mistake-options-purposes-general.trycloudflare.com/auth/callback",
  "https://mistake-options-purposes-general.trycloudflare.com/auth/shopify/callback",
  "https://mistake-options-purposes-general.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
