# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6750de2a7fb129090141301871506741"
name = "app-tmt"
handle = "app-tmt"
application_url = "https://pet-chairs-trackbacks-terminology.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://pet-chairs-trackbacks-terminology.trycloudflare.com/auth/callback",
  "https://pet-chairs-trackbacks-terminology.trycloudflare.com/auth/shopify/callback",
  "https://pet-chairs-trackbacks-terminology.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
